project:
  type: website
  output-dir: docs

website:
  title: "STA 9750"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mp01.qmd
        text: Mini-Project 1
      - href: mp02.qmd
        text: Mini-Project 2
      - href: mp03.qmd
        text: Mini-Project 3
      - href: mp04.qmd
        text: Mini-Project 4

format:
  html:
    toc: true

execute:
  freeze: auto